#!/usr/bin/env bash
set -euo pipefail

LLVM_VER=${LLVM_VER:-22.1.8}
CMAKE_VER=${CMAKE_VER:-4.4.2}
NINJA_VER=${NINJA_VER:-1.13.2}
RUST_TARGET=x86_64-unknown-linux-musl

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
BASE=${LLVM_BOOTSTRAP_DIR:-$ROOT/target/llvm}
SRC=$BASE/src
BUILD=$BASE/build
PREFIX=$BASE/prefix
TOOLS=$BASE/tools
TC=$TOOLS/x86_64-linux-musl-cross
STAMP=$PREFIX/.stamp-$LLVM_VER
JOBS=${JOBS:-$(nproc)}

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
die() {
    printf '\033[1;31merror:\033[0m %s\n' "$*" >&2
    exit 1
}

mkdir -p "$SRC" "$BUILD" "$TOOLS/bin"
export PATH=$TOOLS/bin:$PATH

if [ ! -x "$TC/bin/x86_64-linux-musl-g++" ]; then
    log "fetching musl cross toolchain"
    curl -fsSL -o "$TOOLS/mc.tgz" https://musl.cc/x86_64-linux-musl-cross.tgz ||
        curl -fsSL -o "$TOOLS/mc.tgz" https://more.musl.cc/11/x86_64-linux-musl/x86_64-linux-musl-cross.tgz
    tar xzf "$TOOLS/mc.tgz" -C "$TOOLS"
    rm -f "$TOOLS/mc.tgz"
fi

# rustc emits -lstdc++ after -Wl,-Bdynamic, which prefers the .so. We only ever
# want static C++, so remove the shared copy from our own toolchain tree.
rm -f "$TC"/x86_64-linux-musl/lib/libstdc++.so*
[ -f "$TC/x86_64-linux-musl/lib/libstdc++.a" ] || die "toolchain has no static libstdc++"

if [ ! -x "$TOOLS/bin/cmake" ]; then
    log "fetching cmake $CMAKE_VER"
    curl -fsSL "https://github.com/Kitware/CMake/releases/download/v$CMAKE_VER/cmake-$CMAKE_VER-linux-x86_64.tar.gz" |
        tar xz -C "$TOOLS" --strip-components=1
fi

if [ ! -x "$TOOLS/bin/ninja" ]; then
    log "fetching ninja $NINJA_VER"
    curl -fsSL -o "$BASE/ninja.zip" "https://github.com/ninja-build/ninja/releases/download/v$NINJA_VER/ninja-linux.zip"
    unzip -oq "$BASE/ninja.zip" -d "$TOOLS/bin"
    chmod +x "$TOOLS/bin/ninja"
    rm -f "$BASE/ninja.zip"
fi

rustup target list --installed 2>/dev/null | grep -qx "$RUST_TARGET" ||
    { log "adding rust target $RUST_TARGET"; rustup target add "$RUST_TARGET"; }

write_cargo_config() {
    mkdir -p "$ROOT/.cargo"
    cat >"$ROOT/.cargo/config.toml" <<EOF
# Generated by bootstrap.sh. Absolute paths: cargo does not resolve
# [target.*].linker relative to this file.
[build]
target = "$RUST_TARGET"

[env]
LLVM_SYS_221_PREFIX = "$PREFIX"
CC_x86_64_unknown_linux_musl = "$TC/bin/x86_64-linux-musl-gcc"
CXX_x86_64_unknown_linux_musl = "$TC/bin/x86_64-linux-musl-g++"
AR_x86_64_unknown_linux_musl = "$TC/bin/x86_64-linux-musl-ar"

[target.$RUST_TARGET]
linker = "$TC/bin/x86_64-linux-musl-gcc"
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-static-libstdc++",
    "-C", "link-arg=-static-libgcc",
    # rustc emits -lc before -lstdc++; libstdc++.a's libc references are still
    # unresolved at that point, so libc has to appear again after it.
    "-C", "link-arg=-Wl,-Bstatic",
    "-C", "link-arg=-lc",
    "-C", "link-arg=-lm",
]
EOF
}

if [ -f "$STAMP" ]; then
    log "llvm $LLVM_VER already at $PREFIX"
    write_cargo_config
    "$PREFIX/bin/llvm-config" --version --host-target --targets-built
    exit 0
fi

LLVM_SRC=$SRC/llvm-project-$LLVM_VER.src
if [ ! -d "$LLVM_SRC" ]; then
    log "fetching llvm-project $LLVM_VER"
    curl -fsSL "https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VER/llvm-project-$LLVM_VER.src.tar.xz" |
        tar xJ -C "$SRC"
fi

# CMAKE_SYSTEM_NAME is deliberately unset: host and target are both x86_64, and
# static musl binaries run on this glibc host, so llvm-tblgen executes locally
# and LLVM never enters its cross-compile two-stage path.
log "configuring llvm $LLVM_VER: musl, static, BPF only"
cmake -S "$LLVM_SRC/llvm" -B "$BUILD" -G Ninja -Wno-dev --no-warn-unused-cli \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$PREFIX" \
    -DCMAKE_C_COMPILER="$TC/bin/x86_64-linux-musl-gcc" \
    -DCMAKE_CXX_COMPILER="$TC/bin/x86_64-linux-musl-g++" \
    -DCMAKE_C_FLAGS="-static -w -ffunction-sections -fdata-sections" \
    -DCMAKE_CXX_FLAGS="-static -w -ffunction-sections -fdata-sections" \
    -DCMAKE_EXE_LINKER_FLAGS="-static" \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DLLVM_HOST_TRIPLE=x86_64-unknown-linux-musl \
    -DLLVM_TARGETS_TO_BUILD=BPF \
    -DLLVM_ENABLE_PROJECTS= \
    -DLLVM_ENABLE_RUNTIMES= \
    -DBUILD_SHARED_LIBS=OFF \
    -DLLVM_BUILD_LLVM_DYLIB=OFF \
    -DLLVM_LINK_LLVM_DYLIB=OFF \
    -DLLVM_ENABLE_PIC=ON \
    -DLLVM_APPEND_VC_REV=OFF \
    -DLLVM_ENABLE_ASSERTIONS=OFF \
    -DLLVM_ENABLE_WARNINGS=OFF \
    -DLLVM_ENABLE_PEDANTIC=OFF \
    -DLLVM_ENABLE_BINDINGS=OFF \
    -DLLVM_ENABLE_LIBEDIT=OFF \
    -DLLVM_ENABLE_LIBPFM=OFF \
    -DLLVM_ENABLE_LIBXML2=OFF \
    -DLLVM_ENABLE_TERMINFO=OFF \
    -DLLVM_ENABLE_ZLIB=OFF \
    -DLLVM_ENABLE_ZSTD=OFF \
    -DLLVM_ENABLE_CURL=OFF \
    -DLLVM_ENABLE_HTTPLIB=OFF \
    -DLLVM_ENABLE_Z3_SOLVER=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_DOCS=OFF

log "building with $JOBS jobs"
ninja -C "$BUILD" -j "$JOBS"
ninja -C "$BUILD" install

touch "$STAMP"
write_cargo_config
log "installed $("$PREFIX/bin/llvm-config" --version) -> $PREFIX ($(du -sh "$PREFIX" | cut -f1))"
"$PREFIX/bin/llvm-config" --host-target --targets-built --shared-mode

cat <<EOF

wrote .cargo/config.toml -> plain 'cargo build' now targets $RUST_TARGET.
note: 'cargo clean' deletes target/. Set LLVM_BOOTSTRAP_DIR to keep llvm elsewhere.
EOF
