[package]
name = "traqilet"
version = "0.1.0"
edition = "2024"
rust-version = "1.87"

[dependencies]
annotate-snippets = "0.12"
aya = "0.14"
clap = { version = "4.6", features = ["derive"] }
env_logger = "0.11"
inkwell = { version = "0.10", default-features = false }
log = "0.4"
rhai = { version = "=1.25.1", default-features = false }

[features]
default = [
    "inkwell/llvm22-1",
    "inkwell/llvm22-1-force-static",
    "inkwell/no-libffi-linking",
    "inkwell/target-bpf",
]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
