[package]
name = "traqilet"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ariadne = { workspace = true }
aya = { workspace = true }
clap = { workspace = true, features = ["derive"] }
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
traqilet-btf = { workspace = true }
traqilet-lang = { workspace = true }
traqilet-parser = { workspace = true }
