[package]
name = "traqilet"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ariadne = { workspace = true }
aya = { workspace = true }
clap = { workspace = true, features = ["derive"] }
env_logger = { workspace = true }
log = { workspace = true }
logos = { workspace = true }
